@base_url = http://localhost:8088/db/reservas/properties

###
POST {{base_url}}
Content-Type: application/json

{
  "name": "Ponti Marriott Bogotá plus",
  "stars": 4,
  "property_type": "Hotel",
  "city": "Bogotá",
  "address": "Calle Falsa 123",
  "url": "fake.url/pontimarriottbogota"
}