@base_url = http://localhost:8088/db/reservas/property-rooms

###
POST {{base_url}}
Content-Type: application/json

{
  "hotel_property_id": "66199706-6267-4146-8563-bd2606bca95f",
  "room_id": "caa5f8a2-eb5c-47ef-a423-4777fe0a24c3",
  "bedrooms": 1,
  "bathrooms": 1,
  "price_per_night": 450000
}